### ISSUE TITLE
Availability of data for Navier-Stokes

### ISSUE THREAD

**Issue by scaomath** [Zhengyu-Huang/Operator-Learning#17]
Hello, in the Navier-Stokes DeepONet model: 
https://github.com/Zhengyu-Huang/Operator-Learning/blob/b7c484150fb9bb62441deee1f3cbb2ecfec68dc3/Navier-Stokes/nn/DeepONet/learnDeepONet.py#L31-L33

where are the three `.npy` files located? In the data set link, the NS data set contains the input output pair of shapes `(40000, *mesh_size)`, is this the same file to get the vorticity the variable names suggested above?

@Zhengyu-Huang

**Comment by Zhengyu-Huang** [comment]
Hi @scaomath the data are  here https://data.caltech.edu/records/fp3ds-kej20
The input file [NavierStokes_inputs.npy] has 20000 forcing fields
The output file [NavierStokes_outputs.npy] has 20000 vorticity fields

**Comment by scaomath** [comment]
> Hi @scaomath the data are here https://data.caltech.edu/records/fp3ds-kej20 The input file [NavierStokes_inputs.npy] has 20000 forcing fields The output file [NavierStokes_outputs.npy] has 20000 vorticity fields

May I know how to get these three variables?
https://github.com/Zhengyu-Huang/Operator-Learning/blob/b7c484150fb9bb62441deee1f3cbb2ecfec68dc3/Navier-Stokes/nn/DeepONet/learnDeepONet.py#L31-L33

**Comment by Zhengyu-Huang** [comment]
Hi @scaomath , sorry for the confusion here,   

You need first download the data

cs = np.load("NavierStokes_inputs.npy")  
K = np.load("NavierStokes_outputs.npy") 

We do not use theta anymore

**Comment by scaomath** [comment]
Alright thanks.
