### ISSUE TITLE
What discretization is the Helmholtz problem used in the paper?

### ISSUE THREAD

**Issue by scaomath** [Zhengyu-Huang/Operator-Learning#18]
In the paper, it just says "Equation (4.2) is solved using a finite element method on a 100 × 100 grid".  I am not an expert in Julia, but is the `porder` chosen as 2 here for the Helmholtz data generated (i.e., piecewise bi-quadratic conforming element)? Thanks.

https://github.com/Zhengyu-Huang/Operator-Learning/blob/982f5ebed5aade6b70230c7e5c9193312be371ed/Helmholtz/src/Domain.jl#L70-L75

**Comment by Zhengyu-Huang** [comment]
Hi @scaomath , the default value of porder is 2, but for the data set, we use porder=1, namely, piecewise linear conforming element

**Comment by scaomath** [comment]
> Hi @scaomath , the default value of porder is 2, but for the data set, we use porder=1, namely, piecewise linear conforming element

Thanks for the answer.
